### ISSUE TITLE
Installing [Erudite] requires base system updates to #6247 but this system is updated to #6161.

### ISSUE THREAD

**Issue by cstes** [hilaire/drgeo#17]
Just to report that I have raised 

https://github.com/Cuis-Smalltalk/Erudite/issues/19

Because the README of DrGeo suggests to install Cuis6.2 and then to install the Erudite pacakge.

However that seems not possible in the Cuis 6.2 system because there is no git tag BaseForCuis6.2 in the Erudite repo.

Regards,
David Stes

**Comment by hilaire** [comment]
Sadly Stable/Unstable release scheme of Cuis is not operable for now, thus the issues you meet.

**Comment by hilaire** [comment]
Move DrGeo code base to Cuis rolling release for now
