### ISSUE TITLE
DrGeo sur Cuis-Smalltalk-Dev version 6.3

### ISSUE THREAD

**Issue by cstes** [hilaire/drgeo#18]
Bonjour,  j'essaie d'installer DrGeo sur la dernière version Cuis-Smalltalk-Dev 6.3.

Ce qui me semble marcher relativement bien, c'est l'installation des packages SVG, Numerics, Erudite, Parser s sur cette version : l'installation de SVG et Erudite fonctionne sur Cuis-Smalltalk-Dev 6.3 (contrairement à la version Cuis 6.2 pour l'instant, j'ai crée un issue github séparé pour cela).

Si - après l'installation des packages indiqués en haut - je choisis "FileList" dans le menu Cuis, et j'essayé de lire le fichier setupDrGeoDevelopment.st

https://github.com/hilaire/drgeo/blob/main/src/setupDrGeoDevelopment.st

alors ca a l'air d'installerr les packages DrGeo.st

Malheureusement si j'essaie 

DrGeoSystem beDevelopment

je reçois le message d'erreur

**TheWorldMenu doesNotUnderstand:#first**

ce message vient du method **initialize** de DrGDevelopment

Y-a-t-il une façon svp d'installer DrGeo sur la dernieère version Cuis 6.3 ?

Merci !
David Stes
(Flandres, Belgique)

**Comment by hilaire** [comment]
I will take a look

**Comment by hilaire** [comment]
Update your drgeo repo and  extract the change set below in the Cuis-Smalltalk-Dev/CoreUpdates/

It should get it to work. Let me know.

[changeset.zip](https://github.com/hilaire/drgeo/files/14624738/changeset.zip)

**Comment by cstes** [comment]
Hello/Bonjour,

Because you switched to English I'll do so as well but feel free to answer in French or Spanish so I can practice my French skills (or Spanish if you like)..

Anyway thanks a lot for the changeset.zip and the update of the startIDE.sh script !

I think it is working now.

You have to update the README.md file because I am now not exactly following the instructions of the README.md which are/were for Cuis6-2.

Now I created a Cuis folder, then git clone Cuis-Smalltalk-Dev (the rolling release 6.3) and drgeo and I observed that drgeo/cuisVersion was updated to 6.3.

I ran clonePackagesRepos.sh and statusAllRepos.sh from Cuis 6.3.
(that is different than the instructions in the README.md of drgeo)

Anyway then I modified drgeo/startIDE.sh to do:

imageFolder=$imagePath

because I believe you currently have imageFolder not initialized in the startIDE.sh script

I can succesfully extract the changeset.zip under CoreUpdates of Cuis-Smalltalk-Dev.

This results in a file called somenumer-hilaire-something.st

finally when I run

drgeo/startIDE.sh

it succcesfully copies the 6.3 cuis image and loads DrGeo packages

When I run Drgeo new,  I get a sketch window in Cuis so this seems much better now than before

Thanks for your help.
David Stes
