### ISSUE TITLE
Icons newSketch.svg, open.Svg not found for beWorkstation

### ISSUE THREAD

**Issue by cstes** [hilaire/drgeo#24]
When running beDevelopment, DrGeo new displays a window with correct SVG icons.   However when running beWorkstation, for me the DrGeo new message fails with a message that it cannot find newSketch.svg.   I think this is due to the messages rootPath, resourcesPath, iconsPath of DrGDevelopment compared to DrGWorkstation.   I think this is not a bug in fact, I assume that I can simply use the beDevelopment version of DrGeo.   Anyway I am reporting that when I run beWorkstation, the menu displays a System Menu with Tools such as Browse Smalltalk Sketches and Smalltalk Sketch Editor, but at the same time it fails to find the icons from drgeo/resourcse/graphics/iconsSVG/ 

This is simple to solve because when I copy the methods from DrGDevelopment to DrGWorkstation then the DrGeo new message works fine and displays the window just find just as in the beDevelopment case.

What is the goal please of beWorkstatoin ?

**Comment by hilaire** [comment]
You are not supposed to use #beWorkstation when in the DrGeo development environment, may be for some basic testing but not that much.
It is only used in the deployed DrGeo image installed in a workstation bundle (Linux, Windows, Mac). It adjusts the preferences and paths.

The name is a bit misleading, but there were in the past #beAndroid and #beIpad alternatives

**Comment by cstes** [comment]
ok, I can confirm that if I run DrGeoSystem beWorkstation then I get a menu with the SmalltalkSketchEditor in the menu, but as reported I was confused by the doesNotUnderstand message and the failure to find the icons.   The problem with the icons can be easily resolved by implementing the messages like #rootPath, #resourcesPath, #iconsPath of DrGDevelopment compared to DrGWorkstation

Maybe in the Cuis version of DrGeo the #beWorkstation message could be implemented instead by printing an error message that this method is not supposed to be used.

**Comment by hilaire** [comment]
It is just that the path to access the icons is different depending on you are on the drgeo development environment (set by #beDevelopment message) or in a deployed image (set by #beWorkstation).

It does not a problem of unsupported method but about different path to access the resources like the icon.

If you want to have the complete user environment, with the dedicated DrGeo word menu, you should instead build the DrGeo bundle with the ./drgeo/build/makeDrGeo.sh script
