### ISSUE TITLE
Please explain difference between Smalltalk Sketches and DrGeo Sketches

### ISSUE THREAD

**Issue by cstes** [hilaire/drgeo#25]
I am just begining with DrGeo and I am experimenting a bit with the system, but I like the DrGeo new example sketches and also the Smalltalk sketches in the SmalltalkSketchBrowser

Apparently - and this was not clear to me - there seems to be a difference between DrGeo sketches in the resources/sketches directory those are in .fgeo XML format and .png format and the resources/SmalltalkSketches which seem to be in .st format.

For example if I open DrGeo new and then try to open sketches Examples, I can see nice examples like Carré, Point de Fermat,, Cercle Droite d'Euler and many others.

My impression is that those examples are in the resources/sketches directory and they seem to be in .fgeo XML format.

On the other hand if I open the DrGSmalltalkEditor and save some code in MySketches this saves in a different folder called MySmalltalkSketches.

So this is a little bit confusing because I was assuming that the folder MySketches was used for "MySketches" but it is actually a different folder called MySmalltalkSketches.

Is there a relation between the DrGSmalltalkEditor and the DrGeo window please ?  Or are those two different methods of creating skecthes  (one in .Fgeo format and the other one in .st format ) ?

Thanks !
David Stes

**Comment by hilaire** [comment]
David, would you mind to continue the discussion on the DrGeo mailing list?

**Comment by cstes** [comment]
I open issues on github because my understanding is that DrGeo development has moved to, or simply is on, github.   However, if there exists a mailing list that could also be an option.   Can you please give some details or information on the DrGeo mailing list ? Is there a reason not to use github issues for the discussion please ?

**Comment by hilaire** [comment]
Please check out http://gnu.org/s/dr-geo for information on mailing list.
