### ISSUE TITLE
Not possible to build DrGeo on Mac using Macports

### ISSUE THREAD

**Issue by Undreli-Studios** [hilaire/drgeo#37]
Good day team,

I've been trying to build DrGeo on my Mac. Currently I'm not able to do so.

This is the command I execute:
`sudo port install drgeo1`

This is the correct command right? Or maybe DrGeo has another name on Macports?

When I run this command, I get the following errors, which I check by doing `cat /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_drgeo1/drgeo1/main.log`:

```
:info:archivefetch --->  drgeo1-1.1.0_0.darwin_23.x86_64.tbz2 doesn't seem to exist in /opt/local/var/macports/incoming/verified
:msg:archivefetch --->  Attempting to fetch drgeo1-1.1.0_0.darwin_23.x86_64.tbz2 from https://packages.macports.org/drgeo1
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404
:msg:archivefetch --->  Attempting to fetch drgeo1-1.1.0_0.darwin_23.x86_64.tbz2 from https://ywg.ca.packages.macports.org/mirror/macports/packages/drgeo1
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404
:msg:archivefetch --->  Attempting to fetch drgeo1-1.1.0_0.darwin_23.x86_64.tbz2 from https://fra.de.packages.macports.org/drgeo1
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404

[.........]

:info:build drgeo_figure.cc:56:1: error: variable 'drgeoDialogData' is used but not defined in this translation unit, and cannot be defined in any other translation unit because its type does not have linkage
:info:build drgeoDialogData;
:info:build ^
```

So the first three errors seem like Macports is trying to fetch a resource, but it is not found. I checked the three URLs on the browser and the do give 404 errors as stated by the log.

That last error seems more of a coding error, not sure if it is OS related, on file `drgeo_figure.cc:56`.

**Expected behavior**

DrGeo can be installed on Mac through MacPorts.

**Observed behavior**

The command `sudo install port drgeo1` fails with the errors shown.

Thank you for your attention to this issue.

**Comment by hilaire** [comment]
Hi, 

I am of little help. I don't know about Macport.
You try to compile an old branch of DrGeo not developed since 19 years.

What about helping with the newer code branch of DrGeo? 
I have an experimental build for Mac, arranged from Linux. 

https://www.dropbox.com/scl/fi/a49l4pogsua2fb6p1es3r/DrGeo-mac-24.05a-beta.zip?dl=0&rlkey=3yexgm5bo1aw2cqkuwiz0z5wz&st=1p3252pc

I think there are still issues to make it run, but you can have a look at how I organized the app and help to fix it.

Thanks!
